from django.urls import path
from .views import (
    # admin
        register_user_admin,
        SelectClassTeacher,
        SelectClassStudent,
        manage_ticket_notification,
        edit_notification,
        manage_festivals,
        delete_festival,
        answer_support_ticket,
        requests,
        answer_request,
        admin_manage_gallery,
        delete_gallery_image,
        manage_news,
        delete_new,
        edit_new,
        manage_blog,
        edit_blog_post,
        delete_blog_post,
    #student
        student_score,
        student_homework,
        student_exam,
        sample_exams,
        make_ticket,
        festivals,
        festival_parts,
        participate_in_festival,
        student_request,
    #teacher
        manage_score,
        teacher_update_scores,
        manage_homework,
        delete_homework,
        manage_exam,
        edit_exam,
        delete_exam,
        edit_examScore,
        change_student_examscore,
        manage_sample_exams,
        delete_sample_exam,
        answer_ticket,
)

urlpatterns = [
    # admin views:
    path('register/', register_user_admin),
    path('register/teacher-class', SelectClassTeacher),
    path('register/student-class', SelectClassStudent),
    path('manage-tickets-notifs/', manage_ticket_notification),
    path('manage-tickets-notifs/<int:id>/edit-notif/', edit_notification),
    path('manage-tickets-notifs/<int:id>/answer/', answer_support_ticket),
    path('manage-festivals/', manage_festivals),
    path('manage-festivals/<int:id>/delete', delete_festival),
    path('requests/', requests),
    path('requests/<int:id>', answer_request),
    path('manage-gallery/', admin_manage_gallery),
    path('manage-gallery/<int:id>/delete', delete_gallery_image),
    path('manage-news/', manage_news),
    path('manage-news/<int:id>/delete', delete_new),
    path('manage-news/<slug>/edit', edit_new),
    path('manage-blog/', manage_blog),
    path('manage-blog/<slug>/edit', edit_blog_post),
    path('manage-blog/<slug>/delete', delete_blog_post),
    # teachers views:
    path('manage-scores/', manage_score),
    path('manage-scores/<str:subject>/<str:student>/', teacher_update_scores),
    path('manage-homeworks/', manage_homework),
    path('manage-homeworks/<int:id>/delete', delete_homework),
    path('manage-exams/', manage_exam),
    path('manage-exams/<int:id>/edit/', edit_exam),
    path('manage-exams/<int:id>/scores/', edit_examScore),
    path('manage-exams/<int:id>/scores/<int:student_id>', change_student_examscore),
    path('manage-sample-exams/', manage_sample_exams),
    path('manage-sample-exams/<int:id>/delete/', delete_sample_exam),
    path('manage-exams/<int:id>/delete/', delete_exam),
    path('tickets/<int:id>/answer/', answer_ticket),
    # students views:
    path('scores/', student_score),
    path('homeworks/', student_homework),
    path('exams/', student_exam),
    path('Sample-exams', sample_exams),
    path('tickets/', make_ticket),
    path('festivals/', festivals),
    path('festivals/<int:id>/', festival_parts),
    path('festivals/<int:id>/participate/<str:part>', participate_in_festival),
    path('festivals/<festival_part>/', student_request)
]
