# Generated by Django 4.1.7 on 2023-03-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_img', models.ImageField(upload_to='static/assets/blog/image')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=7000)),
                ('file', models.FileField(upload_to='static/assets/blog/file')),
            ],
        ),
    ]
