# Generated by Django 4.2 on 2023-07-04 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_img', models.ImageField(upload_to='static/assets/blog/image')),
                ('category', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=230)),
                ('content', models.TextField(max_length=7000)),
                ('date', models.DateField(default=datetime.datetime(2023, 7, 4, 8, 12, 0, 549470, tzinfo=datetime.UTC))),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='static/assets/blog/file')),
                ('view', models.IntegerField(default=0)),
            ],
        ),
    ]
