# Generated by Django 4.1.7 on 2023-03-30 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_category_alter_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 30, 19, 43, 2, 460361, tzinfo=datetime.timezone.utc)),
        ),
    ]
