# Generated by Django 4.1.7 on 2023-03-30 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_view_alter_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='asdfadsf', max_length=230),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 30, 19, 48, 39, 545831, tzinfo=datetime.timezone.utc)),
        ),
    ]
