# Generated by Django 4.1.7 on 2023-03-31 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_slug_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 31, 16, 46, 31, 30720, tzinfo=datetime.timezone.utc)),
        ),
    ]
