# Generated by Django 4.1.7 on 2023-03-25 02:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=275)),
                ('content', models.TextField(max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='uploaded_time',
            field=models.CharField(default=datetime.datetime(2023, 3, 25, 2, 42, 44, 175624, tzinfo=datetime.timezone.utc), max_length=100),
        ),
    ]
