# Generated by Django 4.1.7 on 2023-03-25 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0002_news_alter_post_uploaded_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
        migrations.AlterField(
            model_name='post',
            name='uploaded_time',
            field=models.CharField(default=datetime.datetime(2023, 3, 25, 2, 50, 46, 20870, tzinfo=datetime.timezone.utc), max_length=100),
        ),
    ]
