# Generated by Django 4.1.7 on 2023-03-26 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0003_rename_news_new_alter_post_uploaded_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/assets/gallery')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField(max_length=3000)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='uploaded_time',
            field=models.CharField(default=datetime.datetime(2023, 3, 26, 0, 7, 22, 141205, tzinfo=datetime.timezone.utc), max_length=100),
        ),
    ]
