# Generated by Django 4.1.7 on 2023-03-26 00:25

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0004_galleryimage_alter_post_uploaded_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='uploaded_time',
            field=models.CharField(default=datetime.datetime(2023, 3, 26, 0, 25, 1, 381984, tzinfo=datetime.timezone.utc), max_length=100),
        ),
    ]
