# Generated by Django 4.1.7 on 2023-03-27 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0005_galleryimage_date_alter_post_uploaded_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='check_date',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='post',
            name='uploaded_time',
            field=models.CharField(default=datetime.datetime(2023, 3, 27, 18, 28, 19, 149613, tzinfo=datetime.timezone.utc), max_length=100),
        ),
    ]
