# Generated by Django 4.1.7 on 2023-03-28 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0006_alter_homework_check_date_alter_post_uploaded_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleexam',
            name='description',
            field=models.TextField(default='از درس 5 تا 12 است.', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='uploaded_time',
            field=models.CharField(default=datetime.datetime(2023, 3, 28, 0, 16, 41, 495326, tzinfo=datetime.timezone.utc), max_length=100),
        ),
    ]
