# Generated by Django 4.1.7 on 2023-03-30 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0007_sampleexam_description_alter_post_uploaded_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uploaded_time',
            field=models.CharField(default=datetime.datetime(2023, 3, 30, 18, 36, 33, 290434, tzinfo=datetime.timezone.utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='score',
            name='title',
            field=models.CharField(choices=[('semester1', 'ترم اول'), ('semester1 mostamar', 'مستمر ترم اول'), ('semester1 exam', 'نوبت ترم اول'), ('semester2', 'ترم دوم'), ('semester2 mostamar', 'مستمر ترم دوم'), ('semester2 exam', 'نوبت ترم دوم')], max_length=100),
        ),
    ]
