# Generated by Django 4.1.7 on 2023-03-31 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0012_alter_post_uploaded_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
